apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arroyo-api-key
  namespace: arroyo
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: arroyo-api-key
    creationPolicy: Owner
    template:
      data:
        api-key: "{{ .api_key }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: "c936b012-7baf-49c3-9a98-b4a10136d31b"
