apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: arroyo-workers
  namespace: arroyo
  labels:
    app: arroyo
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - arroyo
  selector:
    matchLabels:
      cluster: arroyo-worker
  podMetricsEndpoints:
    - port: admin
      interval: 10s
      scrapeTimeout: 5s
      path: /metrics
