# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.3/deployment.json

apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binance-collector
  template:
    metadata:
      labels:
        app: binance-collector
    spec:
      nodeSelector:
        internet: "true"

      containers:
        - name: binance-collector
          image: custom.io/crypto-collector:v0.3.5
          imagePullPolicy: Always
          env:
            - name: RP_URL
              value: redpanda.redpanda.svc.cluster.local:9093
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
