apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakekeeper
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/cunialino/crypto-lakehouse.git"
      targetRevision: main
      path: deploy/base/lakekeeper
      ref: myrepo
    - repoURL: https://lakekeeper.github.io/lakekeeper-charts
      chart: lakekeeper
      targetRevision: "0.11.0"
      helm:
        valuesObject:
          postgresql:
            enabled: false
          externalDatabase:
            host_read: pg-cluster-ro.cnpg-system.svc.cluster.local
            host_write: pg-cluster-rw.cnpg-system.svc.cluster.local
            database: lakekeeper
            user: "lakekeeper"
            passwordSecret: "lakekeeper-secret"
            passwordSecretKey: "PGPASSWORD"
          catalog:
            extraEnv:
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: lakekeeper-secret
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: lakekeeper-secret
                    key: AWS_SECRET_ACCESS_KEY
              - name: LAKEKEEPER__ENABLE_AWS_SYSTEM_CREDENTIALS
                value: "true"
              - name: LAKEKEEPER__S3_ENABLE_DIRECT_SYSTEM_CREDENTIALS
                value: "true"
              - name: LAKEKEEPER__S3_REQUIRE_EXTERNAL_ID_FOR_SYSTEM_CREDENTIALS
                value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: lakekeeper
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
