apiVersion: batch/v1
kind: Job
metadata:
  name: dbt-build
  namespace: risingwave
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: dbt
          image: custom.io/dbt-model:v0.1.0
          imagePullPolicy: Always
          env:
            - name: GARAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-secret
                  key: AWS_ACCESS_KEY_ID
            - name: GARAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-secret
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
