apiVersion: batch/v1
kind: CronJob
metadata:
  name: risingwave-backup
  namespace: risingwave
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      suspend: true
      backoffLimit: 2
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: backup
            image: ghcr.io/risingwavelabs/risingwave:v3.0.2
            command:
            - ./risingwave/bin/risingwave
            - ctl
            - meta
            - backup-meta
            env:
            - name: RW_META_ADDR
              value: "http://risingwave-meta-headless.risingwave.svc.cluster.local:5690"
            - name: AWS_REGION
              value: "eu-lambronx-1"
            - name: RW_S3_ENDPOINT
              value: "http://garage-svc.garage.svc.cluster.local:3900"
            - name: RW_IS_FORCE_PATH_STYLE
              value: "true"
            envFrom:
            - secretRef:
                name: rustfs-secret
            resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "128Mi"
