apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-secret
  namespace: risingwave
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: rustfs-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        MINIO_USERNAME: "rustfs" 
        MINIO_PASSWORD: "{{ .password }}"
        AWS_ACCESS_KEY_ID: "{{ .id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .key}}"
  data:
    - secretKey: password
      remoteRef:
        key: "a7505f67-ace7-4923-9c36-b3f2010b83eb"
    - secretKey: key
      remoteRef:
        key: "01c16d85-1a29-4581-b417-b416016a58fa"

    - secretKey: id
      remoteRef:
        key: "05c2c173-3de5-4727-80a5-b416016a3c73"
