metaComponent:
  replicas: 3
  extraEnvVars:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xmx1g"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "2Gi"

computeComponent:
  replicas: 2
  extraEnvVars:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xmx1g"
  extraEnvVarsSecret: rustfs-secret
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"

    requests:
      cpu: "1"
      memory: "2Gi"

  extraVolumes:
    - name: schema-storage
      configMap:
        name: rw-proto-schema
  extraVolumeMounts:
    - name: schema-storage
      mountPath: /etc/risingwave/schemas
      readOnly: true

frontendComponent:
  replicas: 1
  extraEnvVars:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xmx1g"
  extraEnvVarsSecret: rustfs-secret
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "2Gi"
  extraVolumes:
    - name: schema-storage
      configMap:
        name: rw-proto-schema
  extraVolumeMounts:
    - name: schema-storage
      mountPath: /etc/risingwave/schemas
      readOnly: true

compactorComponent:
  replicas: 1
  resources:
    limits: { cpu: "1", memory: "1Gi" }
    requests: { cpu: "100m", memory: "256M" }

metaStore:
  postgresql:
    enabled: true
    host: pg-cluster-rw.cnpg-system.svc.cluster.local
    port: 5432
    database: risingwave
    authentication:
      existingSecretName: rw-metastore-secret

stateStore:
  s3:
    enabled: true
    endpoint: "http://garage-svc.garage.svc.cluster.local:3900"
    bucket: hummock001
    region: "eu-lambronx-1"
    forcePathStyle: true
    authentication:
      existingSecretName: rustfs-secret
