metaComponent:
  replicas: 3
  extraEnvVars:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xmx1g"
    - name: RW_CONFIG_PATH
      value: /etc/risingwave/config/risingwave.toml
  resources:
    requests:
      cpu: "20m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"
  extraVolumes:
    - name: rw-config
      configMap:
        name: rw-config
  extraVolumeMounts:
    - name: rw-config
      mountPath: /etc/risingwave/config
      readOnly: true

computeComponent:
  replicas: 2
  extraEnvVars:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xmx1g"
    - name: RW_CONFIG_PATH
      value: /etc/risingwave/config/risingwave.toml
  extraEnvVarsSecret: rustfs-secret
  resources:
    limits:
      cpu: "500m"
      memory: "2Gi"

    requests:
      cpu: "200m"
      memory: "1Gi"

  extraVolumes:
    - name: schema-storage
      configMap:
        name: rw-proto-schema
    - name: rw-config
      configMap:
        name: rw-config
  extraVolumeMounts:
    - name: schema-storage
      mountPath: /etc/risingwave/schemas
      readOnly: true
    - name: rw-config
      mountPath: /etc/risingwave/config
      readOnly: true

frontendComponent:
  replicas: 1
  extraEnvVars:
    - name: JAVA_TOOL_OPTIONS
      value: "-Xmx1g"
    - name: RW_CONFIG_PATH
      value: /etc/risingwave/config/risingwave.toml
  extraEnvVarsSecret: rustfs-secret
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "2Gi"
  extraVolumes:
    - name: schema-storage
      configMap:
        name: rw-proto-schema
    - name: rw-config
      configMap:
        name: rw-config
  extraVolumeMounts:
    - name: schema-storage
      mountPath: /etc/risingwave/schemas
      readOnly: true
    - name: rw-config
      mountPath: /etc/risingwave/config
      readOnly: true

compactorComponent:
  replicas: 1
  extraEnvVars:
    - name: RW_CONFIG_PATH
      value: /etc/risingwave/config/risingwave.toml
  resources:
    limits: { cpu: "500m", memory: "1Gi" }
    requests: { cpu: "50m", memory: "256M" }
  extraVolumes:
    - name: rw-config
      configMap:
        name: rw-config
  extraVolumeMounts:
    - name: rw-config
      mountPath: /etc/risingwave/config
      readOnly: true

metaStore:
  postgresql:
    enabled: true
    host: pg-cluster-rw.cnpg-system.svc.cluster.local
    port: 5432
    database: risingwave
    authentication:
      existingSecretName: rw-metastore-secret

stateStore:
  s3:
    enabled: true
    endpoint: "http://garage-svc.garage.svc.cluster.local:3900"
    bucket: hummock001
    region: "eu-lambronx-1"
    forcePathStyle: true
    authentication:
      existingSecretName: rustfs-secret

monitor:
  podMonitor:
    enabled: true
    additionalLabels:
      release: prometheus

