[package]
name = "crypto-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
futures = "0.3"
anyhow = "1.0.100"
async-nats = "0.44.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
crypto-data = { path = "../crypto-data" }
