apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lakekeeper-secret
  namespace: lakekeeper
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: lakekeeper-secret
    creationPolicy: Owner
    template:
      data:
        PGPASSWORD: "{{ .pg }}"
        AWS_ACCESS_KEY_ID: "{{ .id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .key}}"
  data:
    - secretKey: key
      remoteRef:
        key: "01c16d85-1a29-4581-b417-b416016a58fa"

    - secretKey: id
      remoteRef:
        key: "05c2c173-3de5-4727-80a5-b416016a3c73"

    - secretKey: pg
      remoteRef:
        key: "fc2a2c29-829d-4b72-acc9-b416016fa559"
