apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lakekeeper-secret
  namespace: lakekeeper
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: lakekeeper-secret
    creationPolicy: Owner
    template:
      data:
        PGPASSWORD: "{{ .pg }}"
        AWS_ACCESS_KEY_ID: "{{ .id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .key}}"
  data:
    - secretKey: key
      remoteRef:
        key: "2a8e5b28-2e0a-4548-bb02-b4a300b0ba9d"

    - secretKey: id
      remoteRef:
        key: "4ee71a9a-2d29-4442-b4e8-b4a300b0956b"

    - secretKey: pg
      remoteRef:
        key: "fc2a2c29-829d-4b72-acc9-b416016fa559"
